# Generated by Django 4.2.6 on 2023-11-06 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Basemodel',
            fields=[
                ('id', models.CharField(max_length=256, primary_key=True, serialize=False, unique=True)),
                ('create_time', models.TimeField(auto_now_add=True)),
                ('update_time', models.TimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.basemodel')),
                ('firtsname', models.CharField(max_length=256)),
                ('language', models.IntegerField(choices=[(0, 'Unknown'), (1, 'Uz'), (2, 'Ru')], default=0)),
                ('type', models.IntegerField(choices=[(0, 'Unknown'), (1, 'Student'), (2, 'Parent'), (3, 'Pupil'), (4, 'Job Seeker')], default=0)),
                ('phone_number', models.CharField(max_length=256)),
            ],
            bases=('users.basemodel',),
        ),
    ]
