# Generated by Django 4.2.6 on 2023-11-07 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Basemodel',
            fields=[
                ('id', models.CharField(max_length=256, primary_key=True, serialize=False, unique=True)),
                ('create_time', models.TimeField(auto_now_add=True)),
                ('update_time', models.TimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Webinars',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='webinars.basemodel')),
                ('name_uz', models.CharField(blank=True, max_length=511, null=True)),
                ('name_ru', models.CharField(blank=True, max_length=511, null=True)),
                ('description_uz', models.TextField(blank=True, null=True)),
                ('description_ru', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Webinar date')),
            ],
            bases=('webinars.basemodel',),
        ),
    ]
