# Generated by Django 4.2.6 on 2023-11-07 10:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('webinars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemodel',
            name='id',
            field=models.CharField(default=uuid.uuid4, max_length=256, primary_key=True, serialize=False, unique=True),
        ),
    ]
